---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - migration.k8s-checkpoint-controller
  resources:
  - podmigrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.k8s-checkpoint-controller
  resources:
  - podmigrations/finalizers
  verbs:
  - update
- apiGroups:
  - migration.k8s-checkpoint-controller
  resources:
  - podmigrations/status
  verbs:
  - get
  - patch
  - update
