apiVersion: migration.k8s-checkpoint-controller/v1
kind: PodMigration
metadata:
  labels:
    app.kubernetes.io/name: k8s-checkpoint-controller
    app.kubernetes.io/managed-by: kustomize
  name: podmigration-sample
spec:
  # TODO(user): Add fields here
